/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import grupo.urna.CriaArq;
import java.awt.Dimension;
import java.awt.Toolkit;
import grupo.urna.GeraHashLinha;
import grupo.urna.GeraHashArquivo;
/**
 *
 * @author Luiz
 */
public class TerceiraTela extends javax.swing.JFrame {
    
    private String clienteCC;
    /**
     * Creates new form TerceiraTela
     */
    public TerceiraTela(String informacao) {
        clienteCC = informacao;
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
    }
    private void voltaTela1(){
        PrimeiraTela pt = new PrimeiraTela();
        this.setVisible(false);
        pt.setVisible(true);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnMSatisfeito = new javax.swing.JButton();
        btnSatisfeito = new javax.swing.JButton();
        btnNeutro = new javax.swing.JButton();
        btnInsatisfeito = new javax.swing.JButton();
        btnMInsatisfeito = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Como você avalia o seu atendimento?");

        btnMSatisfeito.setText("Muito Satisfeito");
        btnMSatisfeito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMSatisfeitoActionPerformed(evt);
            }
        });

        btnSatisfeito.setText("Satisfeito");
        btnSatisfeito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSatisfeitoActionPerformed(evt);
            }
        });

        btnNeutro.setText("Neutro");
        btnNeutro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNeutroActionPerformed(evt);
            }
        });

        btnInsatisfeito.setText("Insatisfeito");
        btnInsatisfeito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsatisfeitoActionPerformed(evt);
            }
        });

        btnMInsatisfeito.setText("Muito Insatisfeito");
        btnMInsatisfeito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMInsatisfeitoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMInsatisfeito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnInsatisfeito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNeutro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSatisfeito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMSatisfeito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnMSatisfeito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSatisfeito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNeutro)
                .addGap(18, 18, 18)
                .addComponent(btnInsatisfeito)
                .addGap(18, 18, 18)
                .addComponent(btnMInsatisfeito)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnMSatisfeitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMSatisfeitoActionPerformed
        // TODO add your handling code here:
        CriaArq.salvaNotas("src\\main\\java\\arqs\\Notas.txt", clienteCC + ";5;||"+ GeraHashLinha.geraHashLinha(clienteCC + ";5")+"\n");
        GeraHashArquivo.gerarHashArquivo("src\\main\\java\\arqs\\Notas.txt", "src\\main\\java\\arqs\\hashNotas.txt");
        this.voltaTela1();
    }//GEN-LAST:event_btnMSatisfeitoActionPerformed

    private void btnSatisfeitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSatisfeitoActionPerformed
        // TODO add your handling code here:
        CriaArq.salvaNotas("src\\main\\java\\arqs\\Notas.txt", clienteCC + ";4;||"+ GeraHashLinha.geraHashLinha(clienteCC + ";5")+"\n");
        GeraHashArquivo.gerarHashArquivo("src\\main\\java\\arqs\\Notas.txt", "src\\main\\java\\arqs\\hashNotas.txt");
        this.voltaTela1();
    }//GEN-LAST:event_btnSatisfeitoActionPerformed

    private void btnNeutroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNeutroActionPerformed
        // TODO add your handling code here:
        CriaArq.salvaNotas("src\\main\\java\\arqs\\Notas.txt", clienteCC + ";3;||"+ GeraHashLinha.geraHashLinha(clienteCC + ";5")+"\n");
        GeraHashArquivo.gerarHashArquivo("src\\main\\java\\arqs\\Notas.txt", "src\\main\\java\\arqs\\hashNotas.txt");
        this.voltaTela1();
    }//GEN-LAST:event_btnNeutroActionPerformed

    private void btnInsatisfeitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsatisfeitoActionPerformed
        // TODO add your handling code here:
        CriaArq.salvaNotas("src\\main\\java\\arqs\\Notas.txt", clienteCC + ";2;||"+ GeraHashLinha.geraHashLinha(clienteCC + ";5")+"\n");
        GeraHashArquivo.gerarHashArquivo("src\\main\\java\\arqs\\Notas.txt", "src\\main\\java\\arqs\\hashNotas.txt");
        this.voltaTela1();
    }//GEN-LAST:event_btnInsatisfeitoActionPerformed

    private void btnMInsatisfeitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMInsatisfeitoActionPerformed
        // TODO add your handling code here:
        CriaArq.salvaNotas("src\\main\\java\\arqs\\Notas.txt", clienteCC + ";1;||"+ GeraHashLinha.geraHashLinha(clienteCC + ";5")+"\n");
        GeraHashArquivo.gerarHashArquivo("src\\main\\java\\arqs\\Notas.txt", "src\\main\\java\\arqs\\hashNotas.txt");
        this.voltaTela1();
    }//GEN-LAST:event_btnMInsatisfeitoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TerceiraTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TerceiraTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TerceiraTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TerceiraTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TerceiraTela("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsatisfeito;
    private javax.swing.JButton btnMInsatisfeito;
    private javax.swing.JButton btnMSatisfeito;
    private javax.swing.JButton btnNeutro;
    private javax.swing.JButton btnSatisfeito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
